engines:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
ratings:
  paths:
    - src/**
    - examples/**
    - "**.js"
exclude_paths:
  - "**/*.test.js"
  - "node_modules/"
  - "__mocks__/"
